using System;

// Typo: "Collegctions" should be "Collections"
using System.Collegctions.Generic;
using System.Linq;

// Namespace Typo?: "Valocity" likely intended to be "Velocity".
namespace Utility.Valocity.ProfileHelper
{
    public class People
    {
     // Logic issue:: Under16 is set to 15 years ago, not 16. Also, static initialization with UtcNow means it's fixed at class load. Reimplement correct logic.
     private static readonly DateTimeOffset Under16 = DateTimeOffset.UtcNow.AddYears(-15);
     public string Name { get; private set; }
     public DateTimeOffset DOB { get; private set; }

     // Inconsistent types: Under16.Date is DateTime, but DOB property is DateTimeOffset.
     public People(string name) : this(name, Under16.Date) { }
     // Logic issue: Constructor allows any DOB, including future dates. Consider adding validation to prevent invalid DOBs.
     // Type mismatch: Assigning DateTime to DateTimeOffset property. Should accept DateTimeOffset
     public People(string name, DateTime dob) {
         Name = name;
         DOB = dob;
     }}

    public class BirthingUnit
    {
        /// <summary>
        /// MaxItemsToRetrieve
        /// </summary>
        private List<People> _people;

        public BirthingUnit()
        {
            _people = new List<People>();
        }

        /// <summary>
        /// GetPeoples
        /// </summary>
        /// <param name="j"></param>
        /// <returns>List<object></returns>
        public List<People> GetPeople(int i)
        {
            for (int j = 0; j < i; j++)
            {
                try
                {
                    // Creates a dandon Name
                    string name = string.Empty;
         //Inefficient: Random is re - instantiated inside the loop.Should be created once outside.
                    var random = new Random();
         //Logic Issue: random.Next(0, 1) always returns 0.Name will always be "Bob".
                    if (random.Next(0, 1) == 0) {
                        name = "Bob";
                    }
                    else {
                        name = "Betty";
                    }
                    // Adds new people to the list
                    // Logic issue: DOB is generated by subtracting a random number of years from the current date, but it doesn't account for leap years or varying month lengths.
                    // Consider using a more accurate method for generating DOBs.
                    // Uses 356 days instead of 365, which is incorrect for calculating years. Should use 365 or a more accurate method.
                    _people.Add(new People(name, DateTime.UtcNow.Subtract(new TimeSpan(random.Next(18, 85) * 356, 0, 0, 0))));
                }
                catch (Exception e)
                {
                    // Dont think this should ever happen
                    // Logic Issue: Rethrowing a new exception loses stack trace. 
                    // Catching a general exception and rethrowing a new one with a generic message can obscure the original error. Consider logging the original exception or including its message in the new exception.
                    throw new Exception("Something failed in user creation");
                }
            }
            return _people;
        }

        private IEnumerable<People> GetBobs(bool olderThan30)
        {
            // Logic Issue: should check DOB <= Now - 30 years. Also, same 356-day issue.
            // This method filters people named "Bob" based on their age, but the age calculation is incorrect. 
            return olderThan30 ? _people.Where(x => x.Name == "Bob" && x.DOB >= DateTime.Now.Subtract(new TimeSpan(30 * 356, 0, 0, 0))) : _people.Where(x => x.Name == "Bob");
        }

        public string GetMarried(People p, string lastName)
        {
            if (lastName.Contains("test"))
                return p.Name;
            // Bug: (p.Name.Length + lastName) is invalid. Should concatenate strings before checking length.
            if ((p.Name.Length + lastName).Length > 255)
            {
                // Logic Issue: If the combined length of the name and last name exceeds 255 characters, it attempts to truncate but doesn't actually return the truncated value.
                // The truncation logic is also incorrect as it doesn't account for the space between the first and last name.
                // Substring result is ignored and not used.
                (p.Name + " " + lastName).Substring(0, 255);
            }

            return p.Name + " " + lastName;
        }
    }
}